### ISSUE TITLE
老哥可以加入弹幕功能吗

### ISSUE THREAD

**Issue by bigrain1993** [FlintyLemming/OneIndex-moe-theme#1]
想在视频播放器加弹幕功能～老哥改的很好～

**Comment by qwe7002** [comment]
如果添加弹幕功能的话，目前来看可能需要单独的弹幕服务器实现。

**Comment by FlintyLemming** [comment]
这个需要一个弹幕服务器，关于Dplayer如何添加弹幕，可以简要参考这篇文章
https://www.moerats.com/archives/838/
